apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-api-deployment
  labels:
    app: my-api
spec:
  replicas: 5
  selector:
    matchLabels:
      app: my-api
  template:
    metadata:
      labels:
        app: my-api
    spec:
      containers:
      - name: my-api-container
        image: diegobecerra/api-residencias:latest
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          value: "production"